dist: xenial
language: python
python:
  - "3.7"

services:
  - docker

install:
  - pip install -r requirements.txt
  - pip install codecov pytest-cov

script:
  - pytest --cov=./

# See https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - secure: "DDV4AC5wkNSNjUcfKC8LchCrhDHV1OjuN4TgTOP5y4i4DoJ1AHvHvnpgloBl6SjUwAA4UYiplz8gwEIkOrwd1j6hPEy1dBGC31eWoD8Q1DF4ovSQHsUcp3+WkdpHbcTcK3RY4XQwuMbVkZzwTA9GVflqe1UpRHbiOwEkSmCu1SXWIH+sLr7rrycZdEPuNzJzP8gpaKXuve8UKomHpgsPD8Bg/tGOrL9LpHBdoLebBKWbf2UqO0c9paNP9+llDYKEqEpuDuS9/A9abb8qY4tf4hdV7joSHwjXHl2XUiLtsR9nSuL36bQ7fUrPvXfwp9uQm2+5kp6pXch0bGY/rXGuRdHw1/dle1utFscwswgc74gGrswC2F9vdeuTMK6d+x8eP7Y0T29gVmrAV+NXQm0B+nPiPaNaM1eLluu2mw0s59sj37M0J1D4UMT4q83pRBomRpgiRms+he2Z0HmZ1EAkadXrK8XYW+zgIMuN8s33ERhEDVkOZwjOQYTygrruVGPZL6FNc3QBXsqjUEcoKybIBUQbkyChHWY8/5PdsSbDYS2z7s0LS43G+6zgQfNK+IuLf7Rit3Cv6E2FdjVkV3XV3wH6Tg+3P0q2ddvqQRcRL+b+Uc319lGGXXfpK72KYlI7EPtVTDG7TWVaQgoYrzAm41bQnNf1MfApgDK69JDVWrg="
    - secure: "Ou3HuJaOp1Of9tav5GTNgQvLTgtDAJgOHLGFXmLU9DXISOWNRTgimnREJJfI10A6yOzfHLy45GaiEorQcEgca6ck1zCoSB9XuzdsjmnJIvR1KzXX/PiDSnSORUCpcYACONR+f6tn5gvyz/NlQxY9WmzQ5MET6KYaW0NR7RnigEwYYoQsZnn/e7nYC9kttVUZ7y2XWIUKc/T5fYtECaic7nWuOOnb2iB8qiN5QS1y9yyto/I43p4pYLjYGp4Q9v41TRpyjgMvJC8QrXltsrD843VgNCOCMWijVjj8ndVHOujLWjQfcUfkfbjzQQ8zXZF6vWIaoJgcjrNYDjXBdaSLCUwwaJHVNVvg7LauokXbVY6i7ncapmh7gp11Pw79JlaRyON/HjWceImmZH8w/6xyp/PZhOA1dsViQzng33aNXx5B64/cjtOyG3HNkVsRaN+wRjL6oanymQ10KKIt7vZ7EUJw6mba4zc9xFMrMij4//6lQ22Zjr2mkCxkEbU0Nlw/72PuyFumdrrU1lI9Rd9FH5XLWkLYnp0TBVwoX3lCLxDbL96X85hs/gjqCUy1P4dZPDh3MOU0FJEToi9HvonU/A7lC8As29hFtC0dzCAxHleR12SHTbZ3Glq/QACEK4m9OMleqdC3k+omYzqPYClaUM9q+hlQ1SwyXCrjhHwWdCk="
    - secure: "zFDU2pDOKr9eUFhhDP+KAfjKDXZ8TBZYmcu7blHDp3vuN9lMPSfTMs1+kHou5+KLG5PQhJ9JksM802xD+F6PX9Aew443oLPFKENbQvVv1ypj4jqDkRUcsGDN5PthB6rUXMZiwKZUYs4FXs5RmUQm/x9iOqS/7q0UZCUbXYIJdXjKsIlGz5ZMqF6JJxGyR3+QtoDUkqKWC662GqzifoIXWqu6jJcDCWaWusFYe2DSCSg54KqC1B7VXefN0PDiu/veUjg5K4fcVvbW+ABfdZtpGwFMkF3x2fPQgCrBMqa6bNSdJs64xTJFktr/ZE8Wtk7DDGKLavATThuwF0TD66RRAHQz+J3cb51yJxe4hOuuGkdTIJj/UWoKqg21iZckWYiKUzh6WlZNnVmwa/9EaRt/Ijx0+3dVWgHmFn+INlqm//Qzicw6MRMjj8NhsjtalPfWJUUUVZBS12VW4xEuwQQHYfUykqTl78885EnzdSazUyVgwjHfw88Jfv/jpTq92L8gVESCd6RP27O8fbdMj7kQzMjLGe79SA5xfR+tTHsoVkZG7a7aW6S33HBRievHccjyd56+loYPLB1nWTzpKLr5CooptyME4XN2kxbx2NuyYGfnXiF2tNR64NaAaxRPxH1c6c4ylpINPuoPheZV9YK4lddVmkdGNHVDNDOQbOi3Hq0="

after_success:
  - codecov

# See https://docs.travis-ci.com/user/docker/#building-a-docker-image-from-a-dockerfile
deploy:
  provider: script
  script: bash docker/deploy.sh
  on:
      branch: master
