version: '3'
services:

  mongo:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sample
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
    # Volumes cannot be mounted properly in windows
    # For details, see
    # http://beyondthecorneroffice.com/2018-04-18-MongoDB-on-Windows-Docker/
    # For a workaround see
    # https://blog.jeremylikness.com/blog/2018-12-27_mongodb-on-windows-in-minutes-with-docker/
    # https://stackoverflow.com/questions/37705017/create-named-docker-volume-with-docker-compose
    volumes:
      - mongo_omniboard_db:/data/db
    expose:
      - 27017
    networks:
      - omniboard_fruitclassifier

  omniboard:
    image: vivekratnavel/omniboard:latest
    command: ["--mu", "mongodb://sample:password@mongo:27017/db?authSource=admin"]
    ports:
      - 127.0.0.1:9000:9000
    networks:
      - omniboard_fruitclassifier
    depends_on:
      - mongo

  fruit_classifier:
    image: loeiten/fruit_classifier:latest
    command: ["-m", "app"]
    ports:
      - 0.0.0.0:5000:5000
    volumes:
      - ./../data:/fruit-classifier/data
      - ./../model_files:/fruit-classifier/model_files
      - ./../reports:/fruit-classifier/reports
      - ./../experiment_files:/fruit-classifier/experiment_files
    networks:
      - omniboard_fruitclassifier
    depends_on:
      - omniboard

networks:
  omniboard_fruitclassifier:
    driver: bridge

volumes:
  mongo_omniboard_db:
    external: false